<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field<?= /* @noEscape */
$class ?>">
    <label class="label" for="select_<?= $block->escapeHtmlAttr($_option->getId()) ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>

    <div class="control" style=" max-height : 200px; box-sizing: content-box;overflow: auto;">
        <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_MULTIPLE || $_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_DROP_DOWN) :
            foreach ($_option->getValues() as $value) {
                $image = json_decode($value->getData('image'), true);
                $imageUrl = $image[0]['url'];
            } ?>
            <div>
                <img style="height: auto; width: 60px" src="<?php echo $imageUrl ?>" alt="">
            </div>
            <div>Option Image Space</div>
        <?php endif; ?>

        <?= $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()) : ?>
            <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX) : ?>
                <span id="options-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></span>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
